# Generated by Django 2.0.2 on 2018-03-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dhirajlal_gandhi_college_of_technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=264, unique=True)),
                ('address', models.CharField(max_length=264)),
                ('blood_group', models.CharField(max_length=5)),
                ('mobile_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
