# Generated by Django 2.0.2 on 2018-03-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_app', '0002_auto_20180311_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=264, unique=True)),
                ('batch', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=264)),
                ('blood_group', models.CharField(max_length=5)),
                ('mobile_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dhirajlal_gandhi_college_of_technology',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dhirajlal_gandhi_college_of_technology',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='dhirajlal_gandhi_college_of_technology',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='dhirajlal_gandhi_college_of_technology',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='dhirajlal_gandhi_college_of_technology',
            name='student_name',
        ),
    ]
